name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [6.0.x]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish new version to NuGet
      uses: alirezanet/publish-nuget@v3.0.0
      if: matrix.os == 'ubuntu-latest' && github.event_name != 'pull_request'
      with:
        PROJECT_FILE_PATH: TRENZ.Docs.API.AuthLib/TRENZ.Docs.API.AuthLib.csproj
        INCLUDE_SYMBOLS: true
        VERSION_STATIC: 1.0.0
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
